ALTER TABLE public.projects
DROP COLUMN IF EXISTS parish,
DROP COLUMN IF EXISTS deanery,
DROP COLUMN IF EXISTS nature_of_work,
DROP COLUMN IF EXISTS sort_order,
DROP COLUMN IF EXISTS featured;

ALTER TABLE public.projects 
ADD COLUMN IF NOT EXISTS building_name TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS image_url TEXT,        
ADD COLUMN IF NOT EXISTS image_alt TEXT;      